import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { KINET_DIR } from '../utils/paths.js';

/**
 * Generates the CLAUDE.md file that AI assistants load as their primary context.
 * This is the most important output of KINET — every AI interaction reads it.
 */
export async function generateClaudeMd(context, rulesEngine, config) {
  const rules = rulesEngine.getSummary();
  const prpPath = join(process.cwd(), KINET_DIR, 'prp', 'context.md');
  const customContext = existsSync(prpPath) ? readFileSync(prpPath, 'utf8') : '';

  const sections = [
    header(config),
    stackSection(context),
    architectureSection(context),
    patternsSection(context),
    rulesSection(rules, config.stack),
    testingSection(context),
    commandsSection(),
    skillsSection(config.stack),
    mcpSection(),
    customContext ? `\n---\n\n## Project-Specific Context\n\n${customContext}` : '',
    footer(),
  ];

  return sections.filter(Boolean).join('\n');
}

function header(config) {
  return `# KINET — AI Assistant Context for ${config.projectName}

> This file is auto-generated by [KINET](https://github.com/kinet). Do not edit manually.
> Regenerate with \`kinet update\`.
> Generated: ${new Date().toISOString()}

**You are an AI assistant working on \`${config.projectName}\`.**
All code, plans, and guidance must align with the patterns, rules, and conventions documented here.
When in doubt, follow what's described here — not generic best-practice defaults.
`;
}

function stackSection(ctx) {
  const lines = [`## Tech Stack\n`];
  const t = ctx.tech;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### Frontend (React)`);
    lines.push(`- React ${t.react || 'latest'} — ${t.typescript ? 'TypeScript' : 'JavaScript'}`);
    if (t.bundler && t.bundler !== 'unknown') lines.push(`- Bundler: **${t.bundler}**`);
    if (t.cssFramework && t.cssFramework !== 'unknown') lines.push(`- CSS: **${t.cssFramework}**`);
    if (t.stateManagement) lines.push(`- State: **${t.stateManagement}**`);
    if (t.router && t.router !== 'none') lines.push(`- Router: **${t.router}**`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Backend (Java)`);
    if (t.buildTool) lines.push(`- Build: **${t.buildTool}**`);
    if (t.javaVersion) lines.push(`- Java: **${t.javaVersion}**`);
    if (t.springBoot) lines.push(`- Framework: **Spring Boot**`);
    if (t.lombok) lines.push(`- Lombok: enabled`);
    if (t.mapstruct) lines.push(`- MapStruct: enabled`);
    lines.push('');
  }

  return lines.join('\n');
}

function architectureSection(ctx) {
  const lines = [`## Project Structure\n`];
  const s = ctx.structure;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### Frontend Layout`);
    if (s.hasComponents) lines.push(`- \`src/components/\` — reusable UI components`);
    if (s.hasHooks) lines.push(`- \`src/hooks/\` — custom React hooks`);
    if (s.hasPages) lines.push(`- \`src/pages/\` — route-level page components`);
    if (s.hasServices) lines.push(`- \`src/services/\` — API calls and data fetching`);
    if (s.hasStore) lines.push(`- \`src/store/\` — state management`);
    if (s.hasTypes) lines.push(`- \`src/types/\` — shared TypeScript types`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Backend Layout (layered architecture)`);
    if (s.hasController) lines.push(`- \`controller/\` — REST controllers (thin, delegate to service)`);
    if (s.hasService) lines.push(`- \`service/\` — business logic`);
    if (s.hasRepository) lines.push(`- \`repository/\` — Spring Data repositories`);
    if (s.hasDomain) lines.push(`- \`domain/\` — JPA entities and domain objects`);
    if (s.hasDto) lines.push(`- \`dto/\` — request/response DTOs`);
    if (s.hasConfig) lines.push(`- \`config/\` — Spring configuration classes`);
    lines.push('');
  }

  return lines.join('\n');
}

function patternsSection(ctx) {
  const lines = [`## Coding Patterns\n`];
  const p = ctx.patterns;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### React`);
    lines.push(`- Component style: **${p.componentStyle}** — match existing style in the file`);
    if (p.fetchStrategy && p.fetchStrategy !== 'unknown') {
      lines.push(`- Data fetching: **${p.fetchStrategy}** — use this, do not introduce alternatives`);
    }
    if (p.usesContext) lines.push(`- React Context is used — follow existing context patterns`);
    if (!p.errorBoundary) lines.push(`- No ErrorBoundary detected — add one at page level when building new routes`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Java`);
    lines.push(`- Architecture: **${p.architecture || 'layered'}**`);
    if (p.usesRecords) lines.push(`- Java Records are used for DTOs/value objects`);
    if (p.usesOptional) lines.push(`- Optional<T> is used — never return null from service methods`);
    if (p.exceptionStyle === 'global-handler') lines.push(`- Exception handling: global @ControllerAdvice handler — do not add try/catch in controllers`);
    if (p.validationStyle === 'bean-validation') lines.push(`- Validation: Bean Validation (jakarta.validation) — annotate DTOs, validate at controller boundary`);
    if (p.securityFramework) lines.push(`- Security: ${p.securityFramework} — follow existing SecurityConfig`);
    lines.push('');
  }

  return lines.join('\n');
}

function rulesSection(rules, stack) {
  if (!rules || !rules.length) return '';

  return `## Enforced Rules

The following rules are enforced by KINET. Violations will be flagged by \`kinet validate\`.

${rules.map(r => `### ${r.id}: ${r.name}\n${r.description}\n\n**Applies to:** ${r.scope}`).join('\n\n')}
`;
}

function testingSection(ctx) {
  const lines = [`## Testing Conventions\n`];
  const t = ctx.testing;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    if (t.reactFramework !== 'unknown') lines.push(`- Test framework: **${t.reactFramework}**`);
    if (t.hasRTL) lines.push(`- Use **@testing-library/react** — test behaviour, not implementation`);
    if (t.hasCypress) lines.push(`- E2E: **Cypress**`);
    if (t.hasPlaywright) lines.push(`- E2E: **Playwright**`);
    lines.push(`- Test files: co-locate alongside source (\`*.test.tsx\` next to \`*.tsx\`)`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    if (t.javaFramework !== 'unknown') lines.push(`- Test framework: **${t.javaFramework}**`);
    if (t.hasMockito) lines.push(`- Mocking: **Mockito** — mock at the service boundary`);
    if (t.hasTestContainers) lines.push(`- Integration tests: **Testcontainers** — use real databases`);
    lines.push(`- Unit tests in \`src/test/java\`, mirroring source package structure`);
    lines.push('');
  }

  return lines.join('\n');
}

function commandsSection() {
  return `## AI Commands (Claude Code Slash Commands)

These commands are available in Claude Code. Use them instead of typing freeform prompts.

| Command | Description |
|---------|-------------|
| \`/plan\` | Generate an implementation plan aligned to this project's stack and patterns |
| \`/commit\` | Validate staged changes and generate a conventional commit message |
| \`/pr-review\` | Review the current branch diff against KINET rules and team conventions |
| \`/security\` | Run a security audit of changed files and report OWASP/Spring Security issues |
`;
}

function skillsSection(stack) {
  const skills = ['planning', 'architecture', 'security', 'testing'];
  return `## Available Skills

Skills are deep expertise modules loaded on demand. Reference them explicitly:
"Using the **${stack === 'java' ? 'java-' : 'react-'}security** skill, ..."

${skills.map(s => `- **${s}** — see \`.kinet/skills/${s}.md\``).join('\n')}
`;
}

function mcpSection() {
  return `## MCP Tools (via KINET MCP Server)

These tools are available via the KINET MCP server configured in \`.claude/settings.json\`:

- **kinet_web_search** — search the web for up-to-date library docs and CVEs
- **kinet_github_search** — search this project's GitHub org for existing patterns
- **kinet_get_context** — retrieve distilled project context on demand
- **kinet_get_rules** — fetch current rule set for a specific scope
- **kinet_memory_recall** — recall project-specific AI memories
- **kinet_memory_save** — persist a new memory for future sessions
`;
}

function footer() {
  return `---

*This context was distilled from the live codebase by KINET. If it feels stale, run \`kinet update\`.*`;
}
