import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { KINET_DIR } from '../utils/paths.js';

/**
 * Generates the CLAUDE.md file that AI assistants load as their primary context.
 * This is the most important output of KINET — every AI interaction reads it.
 */
export async function generateClaudeMd(context, rulesEngine, config) {
  const rules = rulesEngine.getSummary();
  const prpPath = join(process.cwd(), KINET_DIR, 'prp', 'context.md');
  const customContext = existsSync(prpPath) ? readFileSync(prpPath, 'utf8') : '';

  const sections = [
    header(config),
    stackSection(context),
    architectureSection(context),
    patternsSection(context),
    rulesSection(rules, config.stack),
    testingSection(context),
    commandsSection(),
    skillsSection(config.stack),
    mcpSection(),
    customContext ? `\n---\n\n## Project-Specific Context\n\n${customContext}` : '',
    footer(),
  ];

  return sections.filter(Boolean).join('\n');
}

function header(config) {
  return `# KINET — AI Assistant Context for ${config.projectName}

> This file is auto-generated by [KINET](https://github.com/kinet). Do not edit manually.
> Regenerate with \`kinet update\`.
> Generated: ${new Date().toISOString()}

**You are an AI assistant working on \`${config.projectName}\`.**
All code, plans, and guidance must align with the patterns, rules, and conventions documented here.
When in doubt, follow what's described here — not generic best-practice defaults.
`;
}

function stackSection(ctx) {
  const lines = [`## Tech Stack\n`];
  const t = ctx.tech;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### Frontend (React)`);
    lines.push(`- React ${t.react || 'latest'} — ${t.typescript ? 'TypeScript' : 'JavaScript'}`);
    if (t.bundler && t.bundler !== 'unknown') lines.push(`- Bundler: **${t.bundler}**`);
    if (t.cssFramework && t.cssFramework !== 'unknown') lines.push(`- CSS: **${t.cssFramework}**`);
    if (t.stateManagement) lines.push(`- State: **${t.stateManagement}**`);
    if (t.router && t.router !== 'none') lines.push(`- Router: **${t.router}**`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Backend (Java)`);
    if (t.buildTool) lines.push(`- Build: **${t.buildTool}**`);
    if (t.javaVersion) lines.push(`- Java: **${t.javaVersion}**`);
    if (t.springBoot) lines.push(`- Framework: **Spring Boot**`);
    if (t.lombok) lines.push(`- Lombok: enabled`);
    if (t.mapstruct) lines.push(`- MapStruct: enabled`);
    lines.push('');
  }

  if (ctx.stack === 'python') {
    lines.push(`### Python`);
    if (t.pythonVersion) lines.push(`- Python: **${t.pythonVersion}**`);
    if (t.packageManager && t.packageManager !== 'unknown') lines.push(`- Package manager: **${t.packageManager}**`);
    if (t.framework && t.framework !== 'none') lines.push(`- Framework: **${t.framework}**`);
    if (t.orm && t.orm !== 'none') lines.push(`- ORM: **${t.orm}**`);
    lines.push('');
  }

  if (ctx.stack === 'salesforce') {
    lines.push(`### Salesforce`);
    if (t.apiVersion) lines.push(`- API version: **${t.apiVersion}**`);
    if (t.packageDirectories?.length) lines.push(`- Package directories: ${t.packageDirectories.map(p => `\`${p}\``).join(', ')}`);
    lines.push(`- LWC: ${t.usesLwc ? 'enabled' : 'not detected'}`);
    if (t.usesAura) lines.push(`- Aura components: present (legacy — prefer LWC for new work)`);
    lines.push('');
  }

  if (ctx.stack === 'node') {
    lines.push(`### Node`);
    if (t.nodeVersion) lines.push(`- Node: **${t.nodeVersion}**`);
    lines.push(`- ${t.typescript ? 'TypeScript' : 'JavaScript'}`);
    if (t.packageManager) lines.push(`- Package manager: **${t.packageManager}**`);
    if (t.framework && t.framework !== 'none') lines.push(`- Framework: **${t.framework}**`);
    if (t.orm && t.orm !== 'none') lines.push(`- ORM: **${t.orm}**`);
    lines.push('');
  }

  if (ctx.stack === 'flutter') {
    lines.push(`### Flutter`);
    if (t.dartSdk) lines.push(`- Dart SDK: **${t.dartSdk}**`);
    if (t.flutterSdk) lines.push(`- Flutter SDK: **${t.flutterSdk}**`);
    if (t.stateManagement && t.stateManagement !== 'none') lines.push(`- State management: **${t.stateManagement}**`);
    lines.push('');
  }

  return lines.join('\n');
}

function architectureSection(ctx) {
  const lines = [`## Project Structure\n`];
  const s = ctx.structure;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### Frontend Layout`);
    if (s.hasComponents) lines.push(`- \`src/components/\` — reusable UI components`);
    if (s.hasHooks) lines.push(`- \`src/hooks/\` — custom React hooks`);
    if (s.hasPages) lines.push(`- \`src/pages/\` — route-level page components`);
    if (s.hasServices) lines.push(`- \`src/services/\` — API calls and data fetching`);
    if (s.hasStore) lines.push(`- \`src/store/\` — state management`);
    if (s.hasTypes) lines.push(`- \`src/types/\` — shared TypeScript types`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Backend Layout (layered architecture)`);
    if (s.hasController) lines.push(`- \`controller/\` — REST controllers (thin, delegate to service)`);
    if (s.hasService) lines.push(`- \`service/\` — business logic`);
    if (s.hasRepository) lines.push(`- \`repository/\` — Spring Data repositories`);
    if (s.hasDomain) lines.push(`- \`domain/\` — JPA entities and domain objects`);
    if (s.hasDto) lines.push(`- \`dto/\` — request/response DTOs`);
    if (s.hasConfig) lines.push(`- \`config/\` — Spring configuration classes`);
    lines.push('');
  }

  if (ctx.stack === 'python') {
    lines.push(`### Python Layout`);
    lines.push(`- Layout: **${s.layout || 'flat-layout'}**`);
    if (s.hasManagePy) lines.push(`- Django project (\`manage.py\` present)`);
    if (s.hasApp) lines.push(`- \`app/\` — application package`);
    if (s.hasModels) lines.push(`- \`models/\` — data models`);
    if (s.hasRoutes) lines.push(`- \`routes/\`/\`api/\` — endpoint definitions`);
    if (s.hasServices) lines.push(`- \`services/\` — business logic`);
    if (s.hasTests) lines.push(`- \`tests/\` — test suite`);
    lines.push('');
  }

  if (ctx.stack === 'salesforce') {
    lines.push(`### Salesforce Layout`);
    lines.push(`- Source root: \`${s.sfdxRoot || 'force-app/main/default'}\``);
    if (s.hasClasses) lines.push(`- \`classes/\` — Apex classes`);
    if (s.hasTriggers) lines.push(`- \`triggers/\` — Apex triggers (delegate to handler classes)`);
    if (s.hasLwc) lines.push(`- \`lwc/\` — Lightning Web Components`);
    if (s.hasAura) lines.push(`- \`aura/\` — Aura components (legacy)`);
    if (s.hasObjects) lines.push(`- \`objects/\` — custom object/field metadata`);
    if (s.hasFlows) lines.push(`- \`flows/\` — declarative automation`);
    lines.push('');
  }

  if (ctx.stack === 'node') {
    lines.push(`### Node Layout`);
    lines.push(`- Source root: \`${s.srcRoot || 'root'}\``);
    if (s.hasRoutes) lines.push(`- \`routes/\` — route definitions`);
    if (s.hasControllers) lines.push(`- \`controllers/\` — request handlers`);
    if (s.hasServices) lines.push(`- \`services/\` — business logic`);
    if (s.hasMiddleware) lines.push(`- \`middleware/\` — Express/Fastify middleware`);
    if (s.hasModels) lines.push(`- \`models/\` — data models`);
    lines.push('');
  }

  if (ctx.stack === 'flutter') {
    lines.push(`### Flutter Layout`);
    if (s.hasScreens) lines.push(`- \`lib/screens/\`/\`lib/pages/\` — top-level screens`);
    if (s.hasWidgets) lines.push(`- \`lib/widgets/\` — reusable widgets`);
    if (s.hasModels) lines.push(`- \`lib/models/\` — data models`);
    if (s.hasServices) lines.push(`- \`lib/services/\`/\`lib/repositories/\` — data access and business logic`);
    if (s.hasProviders) lines.push(`- \`lib/providers/\` — state management`);
    lines.push('');
  }

  return lines.join('\n');
}

function patternsSection(ctx) {
  const lines = [`## Coding Patterns\n`];
  const p = ctx.patterns;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    lines.push(`### React`);
    lines.push(`- Component style: **${p.componentStyle}** — match existing style in the file`);
    if (p.fetchStrategy && p.fetchStrategy !== 'unknown') {
      lines.push(`- Data fetching: **${p.fetchStrategy}** — use this, do not introduce alternatives`);
    }
    if (p.usesContext) lines.push(`- React Context is used — follow existing context patterns`);
    if (!p.errorBoundary) lines.push(`- No ErrorBoundary detected — add one at page level when building new routes`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    lines.push(`### Java`);
    lines.push(`- Architecture: **${p.architecture || 'layered'}**`);
    if (p.usesRecords) lines.push(`- Java Records are used for DTOs/value objects`);
    if (p.usesOptional) lines.push(`- Optional<T> is used — never return null from service methods`);
    if (p.exceptionStyle === 'global-handler') lines.push(`- Exception handling: global @ControllerAdvice handler — do not add try/catch in controllers`);
    if (p.validationStyle === 'bean-validation') lines.push(`- Validation: Bean Validation (jakarta.validation) — annotate DTOs, validate at controller boundary`);
    if (p.securityFramework) lines.push(`- Security: ${p.securityFramework} — follow existing SecurityConfig`);
    lines.push('');
  }

  if (ctx.stack === 'python') {
    lines.push(`### Python`);
    lines.push(`- Type hints: ${p.usesTypeHints ? 'used — keep annotating new public functions' : 'not consistently used'}`);
    if (p.usesDataclasses) lines.push(`- \`@dataclass\` is used for value objects`);
    if (p.usesPydantic) lines.push(`- Pydantic models are used for validation/schemas`);
    if (p.usesAsync) lines.push(`- Async/await is used — keep I/O-bound code non-blocking`);
    lines.push('');
  }

  if (ctx.stack === 'salesforce') {
    lines.push(`### Salesforce`);
    lines.push(`- Sharing: ${p.sharingDeclared ? 'classes declare `with sharing`/`without sharing` explicitly' : 'not consistently declared — flag missing sharing declarations'}`);
    lines.push(`- Triggers: ${p.triggerHandlerPattern ? 'delegate to handler classes' : 'no handler pattern detected — avoid inline trigger logic'}`);
    if (p.usesSecurityEnforced) lines.push(`- CRUD/FLS: \`WITH SECURITY_ENFORCED\`/\`stripInaccessible\` used — follow this pattern for new SOQL/DML`);
    if (p.usesCustomMetadata) lines.push(`- Custom Metadata Types are used for configuration — prefer over hardcoded values`);
    lines.push('');
  }

  if (ctx.stack === 'node') {
    lines.push(`### Node`);
    lines.push(`- Error handling: **${p.errorHandlingStyle || 'inline'}**`);
    if (p.validationLibrary && p.validationLibrary !== 'none') lines.push(`- Request validation: **${p.validationLibrary}**`);
    if (p.usesAsyncAwait) lines.push(`- async/await is used — keep handlers wrapped in try/catch`);
    lines.push('');
  }

  if (ctx.stack === 'flutter') {
    lines.push(`### Flutter`);
    lines.push(`- Widget style: **${p.widgetStyle || 'unknown'}**`);
    if (p.usesConstConstructors) lines.push(`- \`const\` constructors are used — keep using them for static widget subtrees`);
    if (p.usesNamedRoutes) lines.push(`- Named routes are used for navigation`);
    lines.push('');
  }

  return lines.join('\n');
}

function rulesSection(rules, stack) {
  if (!rules || !rules.length) return '';

  return `## Enforced Rules

The following rules are enforced by KINET. Violations will be flagged by \`kinet validate\`.

${rules.map(r => `### ${r.id}: ${r.name}\n${r.description}\n\n**Applies to:** ${r.scope}`).join('\n\n')}
`;
}

function testingSection(ctx) {
  const lines = [`## Testing Conventions\n`];
  const t = ctx.testing;

  if (ctx.stack === 'react' || ctx.stack === 'fullstack') {
    if (t.reactFramework !== 'unknown') lines.push(`- Test framework: **${t.reactFramework}**`);
    if (t.hasRTL) lines.push(`- Use **@testing-library/react** — test behaviour, not implementation`);
    if (t.hasCypress) lines.push(`- E2E: **Cypress**`);
    if (t.hasPlaywright) lines.push(`- E2E: **Playwright**`);
    lines.push(`- Test files: co-locate alongside source (\`*.test.tsx\` next to \`*.tsx\`)`);
    lines.push('');
  }

  if (ctx.stack === 'java' || ctx.stack === 'fullstack') {
    if (t.javaFramework !== 'unknown') lines.push(`- Test framework: **${t.javaFramework}**`);
    if (t.hasMockito) lines.push(`- Mocking: **Mockito** — mock at the service boundary`);
    if (t.hasTestContainers) lines.push(`- Integration tests: **Testcontainers** — use real databases`);
    lines.push(`- Unit tests in \`src/test/java\`, mirroring source package structure`);
    lines.push('');
  }

  if (ctx.stack === 'python') {
    if (t.pythonFramework && t.pythonFramework !== 'unknown') lines.push(`- Test framework: **${t.pythonFramework}**`);
    if (t.hasConftest) lines.push(`- Shared fixtures in \`conftest.py\``);
    lines.push(`- Test files: \`test_*.py\``);
    lines.push('');
  }

  if (ctx.stack === 'salesforce') {
    lines.push(`- Apex: every class needs a corresponding \`*Test.cls\` with \`@isTest\`, asserting behaviour (not just coverage %)`);
    if (t.hasLwcJest) lines.push(`- LWC: Jest tests via \`@salesforce/sfdx-lwc-jest\``);
    lines.push('');
  }

  if (ctx.stack === 'node') {
    if (t.nodeFramework && t.nodeFramework !== 'unknown') lines.push(`- Test framework: **${t.nodeFramework}**`);
    if (t.hasSupertest) lines.push(`- HTTP integration tests: **supertest**`);
    lines.push('');
  }

  if (ctx.stack === 'flutter') {
    if (t.hasFlutterTest) lines.push(`- Test framework: **flutter_test**`);
    if (t.hasMockito) lines.push(`- Mocking: **mockito**/**mocktail**`);
    lines.push(`- Test files: \`test/**/*_test.dart\``);
    lines.push('');
  }

  return lines.join('\n');
}

function commandsSection() {
  return `## AI Commands (Claude Code Slash Commands)

These commands are available in Claude Code. Use them instead of typing freeform prompts.

| Command | Description |
|---------|-------------|
| \`/plan\` | Generate an implementation plan aligned to this project's stack and patterns |
| \`/commit\` | Validate staged changes and generate a conventional commit message |
| \`/pr-review\` | Review the current branch diff against KINET rules and team conventions |
| \`/security\` | Run a security audit of changed files and report OWASP/Spring Security issues |
`;
}

function skillsSection(stack) {
  const skills = ['planning', 'architecture', 'security', 'testing'];
  const prefixes = { java: 'java-', react: 'react-', python: 'python-', salesforce: 'salesforce-', fullstack: 'fullstack-', node: 'node-', flutter: 'flutter-' };
  const prefix = prefixes[stack] || '';
  return `## Available Skills

Skills are deep expertise modules loaded on demand. Reference them explicitly:
"Using the **${prefix}security** skill, ..."

${skills.map(s => `- **${s}** — see \`.kinet/skills/${s}.md\``).join('\n')}
`;
}

function mcpSection() {
  return `## MCP Tools (via KINET MCP Server)

These tools are available via the KINET MCP server configured in \`.claude/settings.json\`:

- **kinet_web_search** — search the web for up-to-date library docs and CVEs
- **kinet_github_search** — search this project's GitHub org for existing patterns
- **kinet_get_context** — retrieve distilled project context on demand
- **kinet_get_rules** — fetch current rule set for a specific scope
- **kinet_memory_recall** — recall project-specific AI memories
- **kinet_memory_save** — persist a new memory for future sessions
`;
}

function footer() {
  return `---

*This context was distilled from the live codebase by KINET. If it feels stale, run \`kinet update\`.*`;
}
